### ISSUE TITLE
Is it possible to write out text and numbers (calculated from variables) in AngelCAD?

### ISSUE THREAD

**Issue by WillAdams** [arnholm/angelcad#1]
I'd like to bypass the whole separate CAM thing and allow modules to write out coordinate information, something along the lines of:

module radiuscut(beginx, beginy, endx, endy) module which had:

writeln("G0 X",beginx, " Y", beginy," Z",safeheight);
writeln("G1 Z",cutheight," F",plungerate);
writeln("G1 X", endx," Y",endy);
writeln("G0 Z",safeheight," F",plungerate);

where plungerate, safeheight, cutheight were all global variables in addition to the parameters used for the module.

See the module "radiuscut"

in https://community.carbide3d.com/uploads/short-url/cb4ilRtY2Hestsi1kbgdht9yM0Z.zip

**Comment by arnholm** [comment]
Yes it is possible in AngelCAD.

OpenSCAD and AngelCAD are unrelated systems and quite different, especially wrt. language. When you talk about a "module" that is an OpenSCAD term only, "modules" do not exist in AngelCAD, they are simply functions that return solids.

It is certainly possible to write out text and numbers from variables in AngelCAD. You can use iostreams to do it, below is your example loosely translated to AngelCAD

```
double plungerate=0, safeheight=0, cutheight=0;

solid@ radiuscut(double beginx, double beginy, double endx, double endy)
{
   // assume plungerate, safeheight, cutheight are global variables 
   cout << "G0 X" << beginx     << " Y" << beginy << " Z" << safeheight << endl;
   cout << "G1 Z" << cutheight  << " F" << plungerate << endl;
   cout << "G1 X" << endx       << " Y" << endy << endl;
   cout << "G0 Z" << safeheight << " F" << plungerate<< endl;
   
   // return some solid (dummy here)
   return sphere(10);
}
```
