### ISSUE TITLE
Angelcad + curated-code-cad

### ISSUE THREAD

**Issue by Irev-Dev** [arnholm/angelcad#2]
Hey @arnholm 

I got a ever expanding list of all of the code-CAD projects that I know of [here](https://kurthutten.com/blog/curated-code-cad/), and also on [Github](https://github.com/Irev-Dev/curated-code-cad). Someone pointed me in the direction of AngelCad recently so I've added though, as a brief summary I've only got:

Another OpenSCAD style project.

Though I would love some feedback from you if you want to add or change it? The context is that it's in a list with many other code-cad projects, so information about how it differentiates is most useful.

Cheers,
Kurt

**Comment by arnholm** [comment]
Hello Kurt
Thanks for including AngelCAD in your list. I will add some info here. AngelCAD has a [user forum](https://forum.abmesh.com/index.php), where new releases are announced and where users can exchange experiiences.

AngelCAD's first idea is to offer an embedded, but general purpose scripting language for Constructive Solid Geometry, i.e. [AngelScript](https://www.angelcode.com/angelscript/). This allows for a natural programming style with true variables, user defined functions and even classes. Programmers should feel at home. AngelCAD sample scripts can be found [here](https://github.com/arnholm/angelcad-samples).

A second idea is to use a fast boolean engine, so [Carve](https://github.com/arnholm/carve) is used for this purpose. This means that AngelCAD is generally many times faster than other mesh based systems.

Lately, AngelCAD can also run OpenSCAD scripts, with featuers sich as DXF import and text support coming in the near future.

Regards
Carsten Arnholm

**Comment by Irev-Dev** [comment]
Fantastic that's much better than what I had. I've edited somewhat let me know if you any changes.

Thanks for you work on AngelCAD too! I'm so surprised at how many of these projects there are, it's really encouraging.
I'll have to give AngelCAD a go at some point too. If you're claiming speed that will be good. I start to get frustrated when OpenSCAD starts to slow down.

**Comment by arnholm** [comment]
Very good, thanks.

**Comment by Irev-Dev** [comment]
Me again.

I also want to add some of the best real-world examples of Code-CAD being used out in the wild. Do you know of any good projects using AngelCad that I can feature?

So far what I've found is:
- [Acedemics using it for reactor design](https://github.com/ukaea/paramak)
- [Lego compatible blocks](https://fxbricks.com/)
- [specialised in-house equipment for drones](https://twitter.com/robsmallshire/status/1343477584458346497)
- [Pruse 3d printer](https://github.com/prusa3d/Original-Prusa-i3)
